#!/bin/bash
# Aupdate 1.4.0

tmpfile=/tmp/aupdate.txt


# Read options/flags
SUMMARY=false
ASK=false
GUI=false
OPTIONS=$(getopt -q -o asgh --long ask,summary,gui,help -- "$@")
for opt in $OPTIONS; do
  case $opt in
    -s) ;&
    --summary)
      SUMMARY=true
      ;;
    -a) ;&
    --ask)
      ASK=true
      ;;
    -g) ;&
    --gui)
      GUI=true
      ;;
    -h) ;&
    --help) ;&
    \?)
      echo -e "USAGE: aupdate [-asgh]\n  -a, --ask      Ask for confirmation before continuing\n  -s, --summary  Summarize packages after installing\n  -g, --gui      Provide information as gui pop-ups\n  -h, --help     Provide this help information"
      exit 0
      ;;
  esac
done


if ! dpkg --compare-versions "$(apt --version | cut -d' ' -f2)" ge 3; then
  echo "ERROR! This version of aupdate requires apt version 3.x or higher."
  exit -1
fi

echo -e "\e[1;34mUPDATE REPOSITORIES\e[0m"
sudo apt update


# Dry-run the upgrade to get list of packages, exit here if there are none.
UPGRADES=$(apt --dry-run upgrade 2>&1 | grep -v "does not have a stable CLI interface" | sed -n '/Upgrading:/,/^  Upgrading: [0-9]/p')
echo
echo "$UPGRADES"

if echo "$UPGRADES" | grep -q "  Upgrading: 0"; then
  echo -e "\e[1;34mNO UPDATES FOUND\e[0m"
  if "$GUI"; then
    notify-send 'No Updates Found' 'There were no available updates.' --icon=system-software-update
  fi
  exit 0
fi


if "$ASK"; then
# Prompt user to continue if ask flag was used.
  read -r -p $'\e[1;34mDo you want to continue? <y/N> \e[0m ' response
  echo
  response=${response,,}    # tolower
  if [[ ! $response =~ ^(yes|y)$ ]]; then
    exit 0
  fi
fi

# Apply the upgrades
# echo -e "\e[1;34mUPGRADE PACKAGES\e[0m"
# sudo apt -y upgrade
# echo -e "\e[1;34mREMOVE UNNESSACARY PACKAGES\e[0m"
# sudo apt -y autoremove
# echo -e "\e[1;34mAUTOCLEAN\e[0m"
# sudo apt -y autoclean


# If any upgrades were found, then save file & show summary
if ! echo "$UPGRADES" | grep -q "  Upgrading: 0"; then
  # Save upgraded packages file
  if [ ! -e "$tmpfile" ]; then
    touch $tmpfile
  fi
  echo -e "$(date) \n\n$UPGRADES" > $tmpfile

   # Show summary
  if $SUMMARY; then
    printf '%.s─' $(seq 1 "$(tput cols)")
    echo -e "$UPGRADES"
    echo

    # Open summary in text editor if GUI flag
    if "$GUI"; then
      xdg-open $tmpfile
    fi
  fi
fi


# Inform user if a reboot is required
if [ -f /var/run/reboot-required ]; then
  echo -e "\e[1;34mREBOOT REQUIRED\e[0m"
  if "$GUI"; then
    notify-send 'Restart Required' 'Please restart to finish updating!' --icon=system-software-update
  fi
else
  if "$GUI"; then
    notify-send 'Update Complete' 'Updates were applied!' --icon=system-software-update
  fi
fi
